# Vagrant configuration.

box_name: bento/ubuntu-20.04
box_version: 202112.19.0

domain: nip.io

infra_network:
  prefix: 24
  network: 192.168.56.0

kubernetes_vip: 192.168.56.10

cluster_cidr: 10.200.0.0/16

infra_provider: virtualbox

servers:
  - id: kube-master-1
    enable: true
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3b
    base_address: 192.168.56.11
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 12288
      cpus: 4
    roles:
      - etcd
      - kube_master
      - kube_worker
      - load_balancer

  - id: kube-master-2
    enable: true
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3c
    base_address: 192.168.56.12
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 12288
      cpus: 4
    roles:
      - etcd
      - kube_master
      - kube_worker
      - load_balancer

  - id: kube-master-3
    enable: true
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3d
    base_address: 192.168.56.13
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 12288
      cpus: 4
    roles:
      - etcd
      - kube_master
      - kube_worker
      - load_balancer

  - id: kube-worker-1
    enable: false
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3e
    base_address: 192.168.56.14
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 12288
      cpus: 4
    roles:
      - kube_worker
    pod_cidr: 10.200.0.0/24

  - id: kube-worker-2
    enable: false
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3f
    base_address: 192.168.56.15
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 12288
      cpus: 4
    roles:
      - kube_worker
    pod_cidr: 10.200.1.0/24

  - id: kube-worker-3
    enable: false
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3g
    base_address: 192.168.56.16
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 12288
      cpus: 4
    roles:
      - kube_worker
    pod_cidr: 10.200.2.0/24

  - id: infra-deployer
    enable: true
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3a
    base_address: 192.168.56.5
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 12288
      cpus: 4
    roles:
      - deployer
